# Use this configuration file to control what RobotPy packages are installed on your RoboRIO

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.2.1"

# Which extra RobotPy components should be installed
components = [
    "apriltag",
    "commands2",
    "cscore",
    # "navx",
    # "pathplannerlib",
    # "phoenix6",
    # "rev",
    "sim",
]

# Other pip packages to install
requires = [
    "robotpy-commands-v2",
    "robotpy-navx",
    "robotpy-pathplannerlib",
    "phoenix6",
    "robotpy-rev",
    "sleipnirgroup-choreolib",
    "robotpy-urcl",

    "requests",
]
